# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
#
# Placeholder hardware configuration. On the target host, run
#   nixos-generate-config
# to generate the real one, then copy it to this location.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
